### ISSUE TITLE
Update Photo#random to support multiple photos

### ISSUE THREAD

**Issue by aaronklaassen** [unsplash/unsplash_rb#18]
The random photo API endpoint now supports a `count` parameter that allows the client to retrieve a set of photos rather than just one. Add support for that here.

https://unsplash.com/documentation#get-a-random-photo

**Comment by ghwilley** [comment]
I can work on that!

**Comment by razasayed** [comment]
@aaronklaassen Please review my PR. I need some help with writing the test.
