### ISSUE TITLE
Add orientation support to Photo#random

### ISSUE THREAD

**Issue by aaronklaassen** [unsplash/unsplash_rb#19]
The API random photo endpoint now supports an `orientation` parameter to filter photos by portrait/landscape/square. Add support for that here.

https://unsplash.com/documentation#get-a-random-photo

**Comment by tjchester** [comment]
I can work on this.

**Comment by aaronklaassen** [comment]
Thanks @tjchester. If you could make a pull request with this change I'll merge it in. 😄

**Comment by aaronklaassen** [comment]
Thanks @tjchester. If you can just make a pull request with these changes I'll merge them in. 😄
