### ISSUE TITLE
Allow category filtering in photo search.

### ISSUE THREAD

**Issue by aaronklaassen** [unsplash/unsplash_rb#5]
The Unsplash API supports narrowing search results by category (https://unsplash.com/documentation#search-photos), but there's no category argument accepted by `Photo#search`.

**Comment by mth4saurabh** [comment]
@aaronklaassen : [Documentation](https://unsplash.com/documentation#search-photos) doesn't seem to have search filter by categories, also as both **photo search** and **Category** endpoint is deprecated I feel the issue itself is redundant and needs a update.

**Comment by aaronklaassen** [comment]
@mth4saurabh Yup you're right. This issue is old and now it's out of date, especially since the category deprecation. Thanks.
