### ISSUE TITLE
Is any way to trigger photo download API from Photo object?

### ISSUE THREAD

**Issue by deepsystm** [unsplash/unsplash_rb#59]
Hi! My Q in subj. Thanks :hand:

**Comment by deepsystm** [comment]
thanks!

**Comment by deepsystm** [comment]
It will be good if you say some words about this on docs\readme.

**Comment by AgoraSecurity** [comment]
Hello,

I have this doubt.

I read the code, changes, etc. but I think there's no direct way of downloading a photo, right?

This is, a method that will either store the file or return a blob (and make the proper HTTP request)

**Comment by lukechesser** [comment]
@AgoraSecurity this is for [triggering a download event](https://unsplash.com/documentation#track-a-photo-download), which is an API requirement. Downloading an actual image is something you do with the `images.unsplash.com` asset URL contained in the `photos.urls.*` fields
