### ISSUE TITLE
Combining `collections` and `query` parameters

### ISSUE THREAD

**Issue by drusepth** [unsplash/unsplash_rb#67]
#### Steps to Reproduce

- Request a random photo using both the `collections` and `query` parameters, e.g.
```
    response = Unsplash::Photo.random(
      collections: [my_collection_id],
      query:       "cats"
    )
```

#### Observed Behaviour

- A random photo from the `my_collection_id` collection is returned, ignoring the `query` parameter.
- This seemed to be by design as per [the API documentation](https://unsplash.com/documentation#get-a-random-photo) (quote below), but there's no warning for using both parameters; I wonder if it just uses whichever is passed first. 

>Note: You can’t use the collections and query parameters in the same request

#### Expected Behaviour

- In an ideal situation, it'd be nice to be able to use both parameters: specifying a list of collections and _also_ searching by keyword within those collections. 
- In a more realistic situation, I suppose some kind of "You can't use both of these keys together" warning would help tinkering coders figure out why one parameter or the other is being ignored. 

#### Technical Notes

- I'm just getting into the Unsplash API and figuring out how I can help spread the awesome images you all have to more creatives, and would love to know if there is some alternative suggestion for combining `collections` with `query` or if it's just entirely not possible.

- For reference, my use-case is generating personalized writing prompts for authors within the context of pre-built worlds within a worldbuilding app. I'm still exploring the options, but my first prototype was to have a collection for sci-fi images, a collection for modern images, fantasy images, historical images, etc (which works all and well), but I'd also like to give authors a bit more control over what's in the prompts they see, both explicitly (e.g. the author says "I want green landscapes" within a sci-fi world) or implicitly (e.g. the author has a redheaded man they haven't fleshed out, so I might want to append "redhead", "male", etc to some search results to better massage the images returned toward their world). 

- I could also make do with just collections or just queries (by having a ton of very specific collections, or by accepting that some queried results across all of Unsplash might not be "writing prompt" material, even if they are great images), but ideally I'm looking for something in the middle.

Thanks for any advice or guidance you can provide!

**Comment by lukechesser** [comment]
@drusepth thanks for opening the issue.

Re the behaviour, I agree it would be nice if the method returned a warning. We'll look into adding that to the library or if you want to take a shot at it, feel free to open a PR.

Thanks for the suggestion

**Comment by drusepth** [comment]
Hey @lukechesser, thanks for the response. 

The API itself isn't open source, is it? If I were to get into the code I'd be much happier adding the feature itself (the ability to combine `collections` and `query` parameters in the same request) to enable integrations like the one I'm shooting to build. Thanks again!

**Comment by lukechesser** [comment]
Ah, yeah the API isn't open source, I meant for adding the warning for other devs using this library. We may try to eventually add the ability to combine collections and keyword queries for the random endpoint, but it's probably unlikely to happen in the near future unfortunately

**Comment by drusepth** [comment]
No worries -- thanks for letting me know. Unsplash is a great resource and I'll definitely be keeping an eye on API changes in the future!
