### ISSUE TITLE
Dead link in `utm_source` warning

### ISSUE THREAD

**Issue by voikya** [unsplash/unsplash_rb#69]
#### Steps to Reproduce

- Attempt to make an API call without configuring the `utm_source` parameter:
```
Unsplash.configure do |config|
  config.application_access_key = KEY
  config.application_secret = SECRET
end
Unsplash::Photo.search("cats")
```

#### Observed Behaviour

- Warning appears in console. The provided link is dead.
```
W, [2019-05-14T11:35:01.126289]  WARN -- : utm_source is required as part of API Terms: https://community.unsplash.com/developersblog/unsplash-api-guidelines
=> [#<Unsplash::Photo:0x00007faabac32690 ...>]
```

#### Expected Behaviour

- The link should go to a real page

#### Technical Notes

This presumably just needs to be updated with a new value. https://github.com/unsplash/unsplash_rb/blob/09dc5b846cee1576c78ffa79d1e31625e559fd64/lib/unsplash/connection.rb#L105

**Comment by aaronklaassen** [comment]
Ah, thanks @voikya. You're right: the updated URL should be `https://unsplash.com/documentation#hotlinking`
