### ISSUE TITLE
undefined method `application_access_key='

### ISSUE THREAD

**Issue by polymer940c** [unsplash/unsplash_rb#70]
#### Steps to Reproduce
Follow Readme to setup
start rails server
-

#### Observed Behaviour

This error occurs `undefined method `application_access_key=' for #<Unsplash::Configuration:0x00007fb668f1aec0> (NoMethodError)`

-

Apparently looking into the code, gem installed not the latest version. defaulting back to previous code of `config.application_id` from the suggested `config.application_access_key`
will make it work again if your unsplash version is not 2.0(unsure which version but def <= 1.4.1) 

suggest changing readme `gem 'unsplash'` to `gem 'unsplash', '~> 2.0.0'`

**Comment by aaronklaassen** [comment]
Yes, v2.0.0 introduced some breaking changes - hence the major version update.

The `application_access_key` accessor was added v1.5.3 with backwards compatibility; `application_id` was deprecated at that point including a warning log message but not actually removed until v2.

You're right though that we could probably use an "upgrading from 1.x" guide.
