### ISSUE TITLE
Add `Accept-Encoding` header to requests

### ISSUE THREAD

**Issue by aaronklaassen** [unsplash/unsplash_rb#80]
All requests should include an `Accept-Encoding: gzip` header. For bonus points, `Accept-Encoding: gzip,br`

**Comment by internethostage** [comment]
Looking into this I discovered we are already adding the accept encoding header. 
The httparty gem we use to handle the requests inherits it from ruby std-lib [Net::HTTP](https://ruby-doc.org/stdlib-2.7.0/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::HTTP-label-Compression) when not declared. 🎉
