### ISSUE TITLE
OAuth gem dependency is EOL

### ISSUE THREAD

**Issue by voikya** [unsplash/unsplash_rb#82]
#### Steps to Reproduce

Install the Unsplash gem

#### Observed Behaviour

Install will succeed, but with a warning:
```
You have installed oauth2 version 1.4.10, which is EOL.
No further support is anticipated for the 1.4.x series.

OAuth2 version 2 is released.
There are BREAKING changes, but most will not encounter them, and upgrading should be easy!

Please see:
• https://github.com/oauth-xx/oauth2#what-is-new-for-v20
• https://github.com/oauth-xx/oauth2/blob/master/CHANGELOG.md

Please upgrade, report issues, and support the project! Thanks, |7eter l-|. l3oling
```

#### Technical Notes

I can see in the Gemspec that Unsplash is locking the `oauth2` gem to v1.x (https://github.com/unsplash/unsplash_rb/blob/7414642a7068a31cc872f5613bc3baff4a1b9428/unsplash.gemspec#L24). If possible, this condition should be relaxed to allow support for newer versions of `oauth2` to be installed.

**Comment by jamesmacwilliam** [comment]
oauth2 outdated faraday dependency is causing issues with other deps, any update on this quick change?

**Comment by arg** [comment]
Thanks for reporting the dependency issue. We've upgraded OAuth dependency to v2
