### ISSUE TITLE
Photo.random doesn't support content_filter

### ISSUE THREAD

**Issue by hbhanoo** [unsplash/unsplash_rb#85]
#### Steps to Reproduce

Photo.random(query: "trees", content_filter: :high)
-

#### Observed Behaviour

Unknown parameter

#### Expected Behaviour

Passthrough to API per https://unsplash.com/documentation#get-a-random-photo

#### Technical Notes

Created a fork for a pull request here:

https://github.com/unsplash/unsplash_rb/compare/master...hbhanoo:unsplash_rb:master

But can't quite figure out what I need to set the BEARER_TOKEN env variable to for the tests (I'm only making public API requests).

**Comment by arg** [comment]
Added in https://github.com/unsplash/unsplash_rb/pull/86. Will be available in [v3.1.0](https://github.com/unsplash/unsplash_rb/releases/tag/v3.1.0)
